# Generated by Django 5.2.17 on 2026-08-14 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "predicted_class",
                    models.CharField(
                        choices=[
                            ("potato_early_blight", "Potato — Early blight"),
                            ("potato_late_blight", "Potato — Late blight"),
                            ("potato_healthy", "Potato — Healthy"),
                            (
                                "pepper_bell_bacterial_spot",
                                "Pepper (bell) — Bacterial spot",
                            ),
                            ("pepper_bell_healthy", "Pepper (bell) — Healthy"),
                            ("tomato_bacterial_spot", "Tomato — Bacterial spot"),
                            ("tomato_early_blight", "Tomato — Early blight"),
                            ("tomato_late_blight", "Tomato — Late blight"),
                            ("tomato_leaf_mold", "Tomato — Leaf mold"),
                            ("tomato_healthy", "Tomato — Healthy"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Model confidence in [0, 1]."),
                ),
                (
                    "model_version",
                    models.CharField(
                        help_text="e.g. 'v0.1.0' — the TFLite model build that produced this.",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("on_device", "On-device TFLite inference"),
                            ("sms_fallback", "SMS symptom-description fallback"),
                        ],
                        default="on_device",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "diagnoses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Advisory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("treatment", "Treatment recommendation"),
                            ("weather", "Weather / spray-window alert"),
                            ("price", "Mandi price comparison"),
                        ],
                        max_length=16,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "delivered_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("app_push", "In-app / push notification"),
                            ("sms", "SMS"),
                            ("voice_call", "Voice call (IVR)"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisories",
                        to="core.diagnosis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "advisories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="scans/%Y/%m/")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="BCP-47-ish language code the farmer captured this in, e.g. 'gu', 'hi'.",
                        max_length=10,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        help_text="Device-local timestamp of when the photo was taken (may be offline)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this record first reached the backend.",
                        null=True,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="core.scan",
            ),
        ),
    ]
