# Generated by Django 5.2.17 on 2026-08-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "class_id",
                    models.CharField(
                        choices=[
                            ("potato_early_blight", "Potato — Early blight"),
                            ("potato_late_blight", "Potato — Late blight"),
                            ("potato_healthy", "Potato — Healthy"),
                            ("pepper_bell_bacterial_spot", "Pepper (bell) — Bacterial spot"),
                            ("pepper_bell_healthy", "Pepper (bell) — Healthy"),
                            ("tomato_bacterial_spot", "Tomato — Bacterial spot"),
                            ("tomato_early_blight", "Tomato — Early blight"),
                            ("tomato_late_blight", "Tomato — Late blight"),
                            ("tomato_leaf_mold", "Tomato — Leaf mold"),
                            ("tomato_healthy", "Tomato — Healthy"),
                        ],
                        max_length=64,
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["class_id", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_id", "language"), name="unique_treatment_class_language"
                    )
                ],
            },
        ),
    ]
