# Generated by Django 5.2.17 on 2026-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_treatmentrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsSession",
            fields=[
                (
                    "phone_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("need_crop", "Waiting for crop selection"),
                            ("need_symptom", "Waiting for symptom selection"),
                        ],
                        default="need_crop",
                        max_length=20,
                    ),
                ),
                ("crop_choice", models.CharField(blank=True, max_length=1)),
                ("language", models.CharField(default="en", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
