# Generated by Django 5.2.17 on 2026-08-15 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_smssession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "diagnosis_accuracy",
                    models.CharField(
                        choices=[
                            ("correct", "Diagnosis looked right"),
                            ("incorrect", "Diagnosis looked wrong"),
                            ("unsure", "Not sure"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "treatment_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helped", "Treatment helped"),
                            ("no_change", "No change yet"),
                            ("worsened", "Got worse"),
                            ("not_applicable", "No treatment applied"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="core.diagnosis",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
